import '@/app/components/globals.css';
import {montserrat} from '@/app/components/fonts'





export const metadata = {
  title: "Gestion_budget",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.svg",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body  className={`${montserrat.className} antialiased`}>{children}</body>
    </html>
  );
}
